//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature_Values
    {
        public Feature_Values()
        {
            this.Products_Features = new HashSet<Products_Features>();
        }
    
        public int FeatureValueId { get; set; }
        public int FeatureId { get; set; }
        public string FeatureValue { get; set; }
    
        public virtual Features Features { get; set; }
        public virtual ICollection<Products_Features> Products_Features { get; set; }
    }
}
