//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Reviews
    {
        public Product_Reviews()
        {
            this.Product_Reviews1 = new HashSet<Product_Reviews>();
        }
    
        public int ReviewId { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public Nullable<short> Rating { get; set; }
        public string ReviewText { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Product_Reviews> Product_Reviews1 { get; set; }
        public virtual Product_Reviews Product_Reviews2 { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
