//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Features
    {
        public int ProductFeatureId { get; set; }
        public int ProductId { get; set; }
        public int FeatureValueId { get; set; }
    
        public virtual Feature_Values Feature_Values { get; set; }
        public virtual Products Products { get; set; }
    }
}
