//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.InvoiceItems = new HashSet<InvoiceItems>();
            this.Product_Gallery = new HashSet<Product_Gallery>();
            this.Product_Reviews = new HashSet<Product_Reviews>();
            this.Product_Tags = new HashSet<Product_Tags>();
            this.Products_Features = new HashSet<Products_Features>();
            this.Stock = new HashSet<Stock>();
            this.User_Favourites = new HashSet<User_Favourites>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Text { get; set; }
        public string ImageName { get; set; }
        public int Fee { get; set; }
        public int DiscountPercent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int FurtherSubCategoryId { get; set; }
        public int FurthestSubCategoryId { get; set; }
        public byte Status { get; set; }
        public string Comment { get; set; }
        public string Article { get; set; }
    
        public virtual ICollection<InvoiceItems> InvoiceItems { get; set; }
        public virtual Product_Categories Product_Categories { get; set; }
        public virtual Product_Categories Product_Categories1 { get; set; }
        public virtual Product_Categories Product_Categories2 { get; set; }
        public virtual Product_Categories Product_Categories3 { get; set; }
        public virtual ICollection<Product_Gallery> Product_Gallery { get; set; }
        public virtual ICollection<Product_Reviews> Product_Reviews { get; set; }
        public virtual ICollection<Product_Tags> Product_Tags { get; set; }
        public virtual ICollection<Products_Features> Products_Features { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<User_Favourites> User_Favourites { get; set; }
    }
}
