//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeGroups
    {
        public SizeGroups()
        {
            this.Product_Sizes = new HashSet<Product_Sizes>();
        }
    
        public int SizeGroup { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Product_Sizes> Product_Sizes { get; set; }
    }
}
