//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public States()
        {
            this.Cities = new HashSet<Cities>();
            this.UsersInformation = new HashSet<UsersInformation>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public string StateEnName { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual ICollection<UsersInformation> UsersInformation { get; set; }
    }
}
