//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInformation
    {
        public int InfoId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string NationalCode { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Gender Gender { get; set; }
        public bool NewsletterMembership { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual States States { get; set; }
        public virtual UsersInformation UsersInformation1 { get; set; }
        public virtual UsersInformation UsersInformation2 { get; set; }
    }
}
