//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouses
    {
        public Warehouses()
        {
            this.Stock1 = new HashSet<Stock>();
        }
    
        public int WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public byte Status { get; set; }
        public int Stock { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Stock> Stock1 { get; set; }
    }
}
