//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chain_Stock
    {
        public int ID { get; set; }
        public Nullable<int> Brand_Code { get; set; }
        public int Branch_code { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Branch_Name { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> FullCost { get; set; }
        public Nullable<byte> IsAvailable { get; set; }
    }
}
