//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountD
    {
        public Nullable<int> Code { get; set; }
        public string Ean_Code { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> NewCost { get; set; }
        public int Counter { get; set; }
    }
}
