//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountH
    {
        public int Code { get; set; }
        public string FDate { get; set; }
        public string SDate { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public Nullable<int> SalesType { get; set; }
    }
}
