//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeyedEntities : DbContext
    {
        public SeyedEntities()
            : base("name=SeyedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiscountD> DiscountD { get; set; }
        public virtual DbSet<DiscountH> DiscountH { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Whs_QTYDocD> Whs_QTYDocD { get; set; }
        public virtual DbSet<Whs_QTYDocH> Whs_QTYDocH { get; set; }
        public virtual DbSet<VW_Para> VW_Para { get; set; }
    }
}
