//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShariatiEntities : DbContext
    {
        public ShariatiEntities()
            : base("name=ShariatiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiscountD> DiscountD { get; set; }
        public virtual DbSet<DiscountH> DiscountH { get; set; }
        public virtual DbSet<Whs_QTYDocD> Whs_QTYDocD { get; set; }
        public virtual DbSet<Whs_QTYDocH> Whs_QTYDocH { get; set; }
        public virtual DbSet<VW_Para> VW_Para { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Types> Types { get; set; }
    
        public virtual ObjectResult<CreateFactorForWebSales_Result> CreateFactorForWebSales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateFactorForWebSales_Result>("CreateFactorForWebSales");
        }
    }
}
