//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string Barcode { get; set; }
        public Nullable<double> Import { get; set; }
        public Nullable<double> Export { get; set; }
        public Nullable<double> Stock1 { get; set; }
        public int Branch { get; set; }
        public Nullable<int> Send { get; set; }
    }
}
