//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types
    {
        public decimal Counter { get; set; }
        public Nullable<int> TypeNo { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Link { get; set; }
        public string NameEng { get; set; }
        public string value1 { get; set; }
        public string value2 { get; set; }
        public string value3 { get; set; }
        public string value4 { get; set; }
        public string value5 { get; set; }
        public string value6 { get; set; }
        public string value7 { get; set; }
        public string value8 { get; set; }
        public string value9 { get; set; }
        public string value10 { get; set; }
        public string value11 { get; set; }
        public string value12 { get; set; }
        public string value13 { get; set; }
        public string value14 { get; set; }
        public string value15 { get; set; }
        public Nullable<int> Id1 { get; set; }
        public Nullable<int> Id2 { get; set; }
        public Nullable<int> Id3 { get; set; }
        public Nullable<int> Id4 { get; set; }
        public Nullable<int> Id5 { get; set; }
        public Nullable<int> Id6 { get; set; }
        public Nullable<int> Id7 { get; set; }
        public Nullable<int> Id8 { get; set; }
        public Nullable<int> Id9 { get; set; }
        public Nullable<int> Id10 { get; set; }
        public Nullable<int> Id11 { get; set; }
        public Nullable<int> Id12 { get; set; }
        public Nullable<int> Id13 { get; set; }
        public Nullable<int> Id14 { get; set; }
        public Nullable<int> Id15 { get; set; }
        public string Note { get; set; }
        public Nullable<int> Code1 { get; set; }
        public Nullable<int> Code2 { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Account { get; set; }
        public Nullable<int> Branch { get; set; }
        public byte[] Pic { get; set; }
        public string OP_Date { get; set; }
        public string CS_Code { get; set; }
        public Nullable<int> CS_Send { get; set; }
        public Nullable<int> LU_State { get; set; }
        public Nullable<int> LY_SIT { get; set; }
        public Nullable<int> Send { get; set; }
        public Nullable<int> Issend { get; set; }
        public Nullable<int> KM { get; set; }
        public Nullable<int> IsExported { get; set; }
    }
}
