//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Categories
    {
        public Product_Categories()
        {
            this.Product_Categories1 = new HashSet<Product_Categories>();
            this.Products = new HashSet<Products>();
            this.Products1 = new HashSet<Products>();
            this.Products2 = new HashSet<Products>();
            this.Products3 = new HashSet<Products>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryTitle { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Product_Categories> Product_Categories1 { get; set; }
        public virtual Product_Categories Product_Categories2 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Products> Products1 { get; set; }
        public virtual ICollection<Products> Products2 { get; set; }
        public virtual ICollection<Products> Products3 { get; set; }
    }
}
